name: 'Library upload'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      path:
        description: Library directory
        required: true
        type: choice
        options:
          - Library1
          - Library2
          - Library3
  # push:
  #   branches: ["main"]
  #   paths:
  #     - "**/App.json"

jobs:
  upload-library:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4

        - name: Install and cache PowerShell modules
          id: psmodulecache
          uses: potatoqualitee/psmodulecache@v6.2.1
          with:
            modules-to-cache: "Evergreen::, VcRedist::, PSAppDeployToolkit:4.0.6"
            updatable: true
            shell: pwsh

        - name: Import default library
          id: import-library1
          if: github.event_name == 'push'
          shell: pwsh
          working-directory: ${{ github.workspace }}
          env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          run: |
            Import-Module -Name "Evergreen", "VcRedist" -Force
            New-Item -Path "${{ github.workspace }}\working" -ItemType Directory -Force

            # Authenticate to the Okta API and import the library
            $params = @{
                ClientId     = "$env:CLIENT_ID"
                ClientSecret = "$env:CLIENT_SECRET"
                Library      = "${{ github.workspace }}\Library1"
                Path         = "${{ github.workspace }}\working"
                ErrorAction  = "Stop"
            }
            & "${{ github.workspace }}\Start-PackageLibraryUpload.ps1" @params

        - name: Import custom library
          id: import-library2
          if: github.event_name == 'workflow_dispatch'
          shell: pwsh
          working-directory: ${{ github.workspace }}
          env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          run: |
            Import-Module -Name "Evergreen", "VcRedist" -Force
            New-Item -Path "${{ github.workspace }}\working" -ItemType Directory -Force

            # Authenticate to the Okta API and import the library
            $params = @{
                ClientId     = "$env:CLIENT_ID"
                ClientSecret = "$env:CLIENT_SECRET"
                Library      = "${{ github.event.inputs.path }}"
                Path         = "${{ github.workspace }}\working"
                ErrorAction  = "Stop"
            }
            & "${{ github.workspace }}\Start-PackageLibraryUpload.ps1" @params
