name: 'Get existing package status from Rimo3'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  package-status:
    runs-on: windows-latest

    steps:
        - uses: actions/checkout@v4

        - name: Install and cache PowerShell modules
          id: psmodulecache
          uses: potatoqualitee/psmodulecache@v6.2.1
          with:
            modules-to-cache: "Evergreen::, VcRedist::, PSAppDeployToolkit:4.0.6"
            updatable: true
            shell: powershell

        - name: Get package
          id: package-status
          shell: powershell
          working-directory: ${{ github.workspace }}
          env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          run: |
            Import-Module -Name "Evergreen", "VcRedist" -Force

            # Authenticate to the Graph API; expects secrets to be passed into environment variables
            $params = @{
                ClientId     = "$env:CLIENT_ID"
                ClientSecret = "$env:CLIENT_SECRET"
                ErrorAction  = "Stop"
            }
            & "${{ github.workspace }}\scripts\Get-PackageStatus.ps1" @params
